from ollama import chatprompt = "Give me a single one -line tagline "
for t in (0,0.7,1.5):
    print("f Temp:(t)")
    for run in range(3):
        response = chat(
            model="llama3.2",
            message=[
                {
                    "role":"user",
                    "content" : prompt
                }
            ]
            option = {temperature }
        )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           